library(tidyverse)
setwd("/Users/rebeccapasteris/Documents/github2/Adv-Data-Journ/Assignments")
getwd()
dispatch <- read_csv("dispatch.csv")
class(dispatch)
dispatch %>% num_range("CallDateTime")
dispatch %>% select(geox, geoy)
dispatch %>% select(CallDateTime) %>% arrange(desc(CallDateTime))
dispatch %>% select(CallDateTime) %>% arrange(CallDateTime)
dispatch %>% summarise(num = n())
dispatch %>% summarise(mode_hour = mode(Hour))
dispatch %>% filter(ExtNatureDisplayName == "TRAFFIC") %>% group_by(PolArea) %>% summarise(num = n()) %>% arrange(desc(num))
dispatch %>% group_by(Hour) %>% summarise(num = n()) %>% arrange(desc(num))
dispatch %>% filter(Address == "11300 S AIRPORT DR") %>% group_by(ExtNatureDisplayName) %>% summarise(num = n()) %>% arrange(desc(num))
