library(tidyverse)
setwd("/Users/rebeccapasteris/Documents/github2/Adv-Data-Journ/Classwork")
getwd()
MLB <- read_csv("MLB_Salaries_1.csv")
class(MLB)
MLB %>% select(Name, Salary) %>% arrange(desc(Salary))
MLB %>% arrange(desc(Tenure))                                        
MLB %>% filter(Team == "Kansas City Royals") %>% arrange(desc(Salary))
MLB %>% filter(POS == "SS") %>% arrange(desc(Salary))
MLB %>% filter(Tenure == 1)
MLB %>% summarise(num = n())
MLB %>% summarise(total_salary = sum(Salary))
MLB %>% summarise(avg_salary = mean(Salary))
teams <- MLB %>% group_by(Team) %>% summarise(total_salary = sum(Salary))
